services:
  main:
    volumes:
      - /groups/branson/home/bransonk/behavioranalysis/code/ScienceBenchmark/data-format/lee2025/data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
