services:
  main:
    volumes:
      - ../../../data/hasnain2024:/app/data:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
