version = "1.0"

[metadata]

[verifier]
timeout_sec = 14400

[agent]
timeout_sec = 86400

[environment]
build_timeout_sec = 600.0
cpus = 16
memory_mb = 65536
storage_mb = 204800
allow_internet = true
mcp_servers = []

[verifier.env]
CLAUDE_CODE_OAUTH_TOKEN = "${CLAUDE_CODE_OAUTH_TOKEN:-}"
CODEX_AUTH_JSON_B64 = "${CODEX_AUTH_JSON_B64:-}"
ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY:-}"
OPENAI_API_KEY = "${OPENAI_API_KEY:-}"

[solution.env]
