services:
  main:
    volumes:
      - /groups/zhang/home/zhangl5/Allen_Brain/visual-behavior-ophys-1.1.0:/app/data/visual-behavior-ophys-1.1.0:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
