#!/bin/bash

# Use this file to solve the task.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"

# Output files go to /app (working directory) where tests expect them
OUTDIR="${1:-/app}"

# Create required documentation files
cat > "$OUTDIR/CONVERSION_NOTES.md" << 'EOF'
# Dataset Conversion Notes
Generated by reference solution.
EOF

cat > "$OUTDIR/README.md" << 'EOF'
# Neural Decoder Dataset Conversion
Reference solution output.
EOF

# Copy convert_data.py to /app so tests can find it
cp "$SCRIPT_DIR/convert_data.py" "$OUTDIR/convert_data.py"

python3 "$SCRIPT_DIR/convert_data.py" --sample --datadir /app/data "$OUTDIR/sample_data.pkl" > "$OUTDIR/conversion_sample_out.txt"
# verify sample
python3 /app/train_decoder.py --verify-only "$OUTDIR/sample_data.pkl" > "$OUTDIR/verification_sample_out.txt"
# train on sample
python3 /app/train_decoder.py "$OUTDIR/sample_data.pkl" > "$OUTDIR/train_decoder_sample_out.txt"
# convert full data
python3 "$SCRIPT_DIR/convert_data.py" --full --datadir /app/data "$OUTDIR/converted_data.pkl" > "$OUTDIR/conversion_full_out.txt"
# verify full data
python3 /app/train_decoder.py --verify-only "$OUTDIR/converted_data.pkl" > "$OUTDIR/verification_full_out.txt"
# train on full data
python3 /app/train_decoder.py --stats-json "$OUTDIR/stats_full.json" "$OUTDIR/converted_data.pkl" > "$OUTDIR/train_decoder_full_out.txt"

# Persist outputs to mounted volume so they survive even with --disable-verification
mkdir -p /logs/verifier/snapshot
cp "$OUTDIR"/*.pkl "$OUTDIR"/*.json "$OUTDIR"/*.txt "$OUTDIR"/*.py "$OUTDIR"/*.md /logs/verifier/snapshot/ 2>/dev/null || true
